collections:
    - name: community.windows
      source: https://galaxy.ansible.com
    - name: community.general
      source: https://galaxy.ansible.com
      version: 5.0.0
   # - name: community.vmware
    #  source: https://galaxy.ansible.com
